name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
    types:
    - labeled

jobs:
  qe:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/qe.yml@main
    with:
      runLint: true
